//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HomePage_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomePage_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.HomePage_Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subramanyam Kasibhat.
        /// </summary>
        internal static string FifthLineBoxOneHeadingOne {
            get {
                return ResourceManager.GetString("FifthLineBoxOneHeadingOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chief executive officer(CEO).
        /// </summary>
        internal static string FifthLineBoxOneHeadingTwo {
            get {
                return ResourceManager.GetString("FifthLineBoxOneHeadingTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anant Kolhar.
        /// </summary>
        internal static string FifthLineBoxThreeHeadingOne {
            get {
                return ResourceManager.GetString("FifthLineBoxThreeHeadingOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vice President - Strategy &amp; Operations.
        /// </summary>
        internal static string FifthLineBoxThreeHeadingTwo {
            get {
                return ResourceManager.GetString("FifthLineBoxThreeHeadingTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savita Kasibhat.
        /// </summary>
        internal static string FifthLineBoxTwoHeadingOne {
            get {
                return ResourceManager.GetString("FifthLineBoxTwoHeadingOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Chief Technology Officer (CTO).
        /// </summary>
        internal static string FifthLineBoxTwoHeadingTwo {
            get {
                return ResourceManager.GetString("FifthLineBoxTwoHeadingTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leadership at vegam.
        /// </summary>
        internal static string FifthLineHeading {
            get {
                return ResourceManager.GetString("FifthLineHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Vegam Employee Portal.
        /// </summary>
        internal static string FirstLineHeadingOne {
            get {
                return ResourceManager.GetString("FirstLineHeadingOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empowering Smart Manufacturing Through You.
        /// </summary>
        internal static string FirstLineHeadingTwo {
            get {
                return ResourceManager.GetString("FirstLineHeadingTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Work Culture.
        /// </summary>
        internal static string FourthLineHeadingOne {
            get {
                return ResourceManager.GetString("FourthLineHeadingOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We foster innovation, collaboration, and continuous learning. Our team works globally, shares knowledge, and thrives together..
        /// </summary>
        internal static string FouthLineHeadingTwo {
            get {
                return ResourceManager.GetString("FouthLineHeadingTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginBtn {
            get {
                return ResourceManager.GetString("LoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Vegam Solutions.
        /// </summary>
        internal static string SecondLineHeadingOne {
            get {
                return ResourceManager.GetString("SecondLineHeadingOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegam Solutions is a global digital manufacturing company offering real-time factory visibility, insights, and control solutions. We innovate for efficiency and excellence in every aspect of your manufacturing process..
        /// </summary>
        internal static string SecondLineHeadingTwo {
            get {
                return ResourceManager.GetString("SecondLineHeadingTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Manufacturing.
        /// </summary>
        internal static string ThirdLineFirstBoxHeadingOne {
            get {
                return ResourceManager.GetString("ThirdLineFirstBoxHeadingOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digitize your shop floor for real-time data-driven decisions..
        /// </summary>
        internal static string ThirdLineFirstBoxHeadingTwo {
            get {
                return ResourceManager.GetString("ThirdLineFirstBoxHeadingTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Core Solutions.
        /// </summary>
        internal static string ThirdLineHeadingOne {
            get {
                return ResourceManager.GetString("ThirdLineHeadingOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IoT Integrations.
        /// </summary>
        internal static string ThirdLineSecondBoxHeadingOne {
            get {
                return ResourceManager.GetString("ThirdLineSecondBoxHeadingOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect assets and monitor them with intelligent IoT layers..
        /// </summary>
        internal static string ThirdLineSecondBoxHeadingTwo {
            get {
                return ResourceManager.GetString("ThirdLineSecondBoxHeadingTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics &amp; Insights.
        /// </summary>
        internal static string ThirdLineThirdBoxHeadingOne {
            get {
                return ResourceManager.GetString("ThirdLineThirdBoxHeadingOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access actionable KPIs, downtime data, and predictive reports..
        /// </summary>
        internal static string ThirdLineThirdBoxHeadingTwo {
            get {
                return ResourceManager.GetString("ThirdLineThirdBoxHeadingTwo", resourceCulture);
            }
        }
    }
}
