//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HRPage_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HRPage_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.HRPage_Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string AcceptBtn {
            get {
                return ResourceManager.GetString("AcceptBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        internal static string AcceptedBtn {
            get {
                return ResourceManager.GetString("AcceptedBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string ActionCol {
            get {
                return ResourceManager.GetString("ActionCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddBtn {
            get {
                return ResourceManager.GetString("AddBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteBtn {
            get {
                return ResourceManager.GetString("DeleteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string DepartmentBtn {
            get {
                return ResourceManager.GetString("DepartmentBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string DepartmentCol {
            get {
                return ResourceManager.GetString("DepartmentCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dept ID.
        /// </summary>
        internal static string DeptIdCol {
            get {
                return ResourceManager.GetString("DeptIdCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ID.
        /// </summary>
        internal static string EmailIDCol {
            get {
                return ResourceManager.GetString("EmailIDCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmpID.
        /// </summary>
        internal static string EmpIDCol {
            get {
                return ResourceManager.GetString("EmpIDCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstNameCol {
            get {
                return ResourceManager.GetString("FirstNameCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR.
        /// </summary>
        internal static string HRBtn {
            get {
                return ResourceManager.GetString("HRBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR.
        /// </summary>
        internal static string HRButton {
            get {
                return ResourceManager.GetString("HRButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Of HRs.
        /// </summary>
        internal static string HRHeading {
            get {
                return ResourceManager.GetString("HRHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR ID.
        /// </summary>
        internal static string HRIDHeading {
            get {
                return ResourceManager.GetString("HRIDHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR Name.
        /// </summary>
        internal static string HRNameHeading {
            get {
                return ResourceManager.GetString("HRNameHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to HR DashBoard.
        /// </summary>
        internal static string HRPageHeading {
            get {
                return ResourceManager.GetString("HRPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastNameCol {
            get {
                return ResourceManager.GetString("LastNameCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextBtn {
            get {
                return ResourceManager.GetString("NextBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string PendingBtn {
            get {
                return ResourceManager.GetString("PendingBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string PrevBtn {
            get {
                return ResourceManager.GetString("PrevBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string RejectBtn {
            get {
                return ResourceManager.GetString("RejectBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string RejectedBtn {
            get {
                return ResourceManager.GetString("RejectedBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected Reason.
        /// </summary>
        internal static string RejectedReasonCol {
            get {
                return ResourceManager.GetString("RejectedReasonCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string ResumeCol {
            get {
                return ResourceManager.GetString("ResumeCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string StatusCol {
            get {
                return ResourceManager.GetString("StatusCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Accepted Employee Count.
        /// </summary>
        internal static string TotalAcceptedEmpCount {
            get {
                return ResourceManager.GetString("TotalAcceptedEmpCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string TotalBtn {
            get {
                return ResourceManager.GetString("TotalBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Department Count.
        /// </summary>
        internal static string TotalDeptCount {
            get {
                return ResourceManager.GetString("TotalDeptCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Count.
        /// </summary>
        internal static string TotalEmpCount {
            get {
                return ResourceManager.GetString("TotalEmpCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total HR Count.
        /// </summary>
        internal static string TotalHRCount {
            get {
                return ResourceManager.GetString("TotalHRCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Pending Employee Count.
        /// </summary>
        internal static string TotalPendingEmpCount {
            get {
                return ResourceManager.GetString("TotalPendingEmpCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Rejected Employee Count.
        /// </summary>
        internal static string TotalRejectedEmpCount {
            get {
                return ResourceManager.GetString("TotalRejectedEmpCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Department.
        /// </summary>
        internal static string TotDeptHeading {
            get {
                return ResourceManager.GetString("TotDeptHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName:.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string UserNameCol {
            get {
                return ResourceManager.GetString("UserNameCol", resourceCulture);
            }
        }
    }
}
