//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPAS.Registration_ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Registration_ServiceReference.IRegistrationService")]
    public interface IRegistrationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationService/GetDepartment", ReplyAction="http://tempuri.org/IRegistrationService/GetDepartmentResponse")]
        iPAS_Service.DepartmentListInfo GetDepartment();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationService/GetDepartment", ReplyAction="http://tempuri.org/IRegistrationService/GetDepartmentResponse")]
        System.Threading.Tasks.Task<iPAS_Service.DepartmentListInfo> GetDepartmentAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationService/InsertNewRegisteredUser", ReplyAction="http://tempuri.org/IRegistrationService/InsertNewRegisteredUserResponse")]
        iPAS_Service.RegistrationInfo InsertNewRegisteredUser(iPAS_Service.RegistrationInfo newUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationService/InsertNewRegisteredUser", ReplyAction="http://tempuri.org/IRegistrationService/InsertNewRegisteredUserResponse")]
        System.Threading.Tasks.Task<iPAS_Service.RegistrationInfo> InsertNewRegisteredUserAsync(iPAS_Service.RegistrationInfo newUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationService/BindLanguages", ReplyAction="http://tempuri.org/IRegistrationService/BindLanguagesResponse")]
        iPAS_Service.RegistrationInfo BindLanguages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationService/BindLanguages", ReplyAction="http://tempuri.org/IRegistrationService/BindLanguagesResponse")]
        System.Threading.Tasks.Task<iPAS_Service.RegistrationInfo> BindLanguagesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegistrationServiceChannel : IPAS.Registration_ServiceReference.IRegistrationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrationServiceClient : System.ServiceModel.ClientBase<IPAS.Registration_ServiceReference.IRegistrationService>, IPAS.Registration_ServiceReference.IRegistrationService {
        
        public RegistrationServiceClient() {
        }
        
        public RegistrationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistrationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public iPAS_Service.DepartmentListInfo GetDepartment() {
            return base.Channel.GetDepartment();
        }
        
        public System.Threading.Tasks.Task<iPAS_Service.DepartmentListInfo> GetDepartmentAsync() {
            return base.Channel.GetDepartmentAsync();
        }
        
        public iPAS_Service.RegistrationInfo InsertNewRegisteredUser(iPAS_Service.RegistrationInfo newUser) {
            return base.Channel.InsertNewRegisteredUser(newUser);
        }
        
        public System.Threading.Tasks.Task<iPAS_Service.RegistrationInfo> InsertNewRegisteredUserAsync(iPAS_Service.RegistrationInfo newUser) {
            return base.Channel.InsertNewRegisteredUserAsync(newUser);
        }
        
        public iPAS_Service.RegistrationInfo BindLanguages() {
            return base.Channel.BindLanguages();
        }
        
        public System.Threading.Tasks.Task<iPAS_Service.RegistrationInfo> BindLanguagesAsync() {
            return base.Channel.BindLanguagesAsync();
        }
    }
}
