//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPAS.Employee_ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Employee_ServiceReference.IEmployeeService")]
    public interface IEmployeeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/FetchEmployeeData", ReplyAction="http://tempuri.org/IEmployeeService/FetchEmployeeDataResponse")]
        iPAS_Service.RegistrationInfo FetchEmployeeData(iPAS_Service.RegistrationInfo employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/FetchEmployeeData", ReplyAction="http://tempuri.org/IEmployeeService/FetchEmployeeDataResponse")]
        System.Threading.Tasks.Task<iPAS_Service.RegistrationInfo> FetchEmployeeDataAsync(iPAS_Service.RegistrationInfo employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/updateEmployeeData", ReplyAction="http://tempuri.org/IEmployeeService/updateEmployeeDataResponse")]
        bool updateEmployeeData(iPAS_Service.RegistrationInfo employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/updateEmployeeData", ReplyAction="http://tempuri.org/IEmployeeService/updateEmployeeDataResponse")]
        System.Threading.Tasks.Task<bool> updateEmployeeDataAsync(iPAS_Service.RegistrationInfo employee);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeServiceChannel : IPAS.Employee_ServiceReference.IEmployeeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServiceClient : System.ServiceModel.ClientBase<IPAS.Employee_ServiceReference.IEmployeeService>, IPAS.Employee_ServiceReference.IEmployeeService {
        
        public EmployeeServiceClient() {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public iPAS_Service.RegistrationInfo FetchEmployeeData(iPAS_Service.RegistrationInfo employee) {
            return base.Channel.FetchEmployeeData(employee);
        }
        
        public System.Threading.Tasks.Task<iPAS_Service.RegistrationInfo> FetchEmployeeDataAsync(iPAS_Service.RegistrationInfo employee) {
            return base.Channel.FetchEmployeeDataAsync(employee);
        }
        
        public bool updateEmployeeData(iPAS_Service.RegistrationInfo employee) {
            return base.Channel.updateEmployeeData(employee);
        }
        
        public System.Threading.Tasks.Task<bool> updateEmployeeDataAsync(iPAS_Service.RegistrationInfo employee) {
            return base.Channel.updateEmployeeDataAsync(employee);
        }
    }
}
