//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPAS.Login_ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Login_ServiceReference.ILogin")]
    public interface ILogin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/UserCredential", ReplyAction="http://tempuri.org/ILogin/UserCredentialResponse")]
        iPAS_Service.RegistrationInfo UserCredential(iPAS_Service.RegistrationInfo user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/UserCredential", ReplyAction="http://tempuri.org/ILogin/UserCredentialResponse")]
        System.Threading.Tasks.Task<iPAS_Service.RegistrationInfo> UserCredentialAsync(iPAS_Service.RegistrationInfo user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginChannel : IPAS.Login_ServiceReference.ILogin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginClient : System.ServiceModel.ClientBase<IPAS.Login_ServiceReference.ILogin>, IPAS.Login_ServiceReference.ILogin {
        
        public LoginClient() {
        }
        
        public LoginClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public iPAS_Service.RegistrationInfo UserCredential(iPAS_Service.RegistrationInfo user) {
            return base.Channel.UserCredential(user);
        }
        
        public System.Threading.Tasks.Task<iPAS_Service.RegistrationInfo> UserCredentialAsync(iPAS_Service.RegistrationInfo user) {
            return base.Channel.UserCredentialAsync(user);
        }
    }
}
